### ISSUE TITLE
Source code structure

### ISSUE THREAD

**Issue by vraravam** [jhipster/jhipster-net#4]
##### **Overview of the issue**
I was trying to understand and write some unit tests to contribute to this new codebase. Not sure if this base folder under `src` is where things should go. Any explanation for the thought process would be good.

##### **Motivation for or Use Case**
Contributing to the codebase by adding unit tests seems unintuitive.

##### **Related issues**
Not that I know of - this is issue numero uno for this codebase

##### **JHipster Version(s)**
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/dev/oss/jhipster-net
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

git version 2.28.0

node: v13.5.0

npm: 6.13.4

Docker version 19.03.12, build 48a66213fe

docker-compose version 1.26.2, build eefe0d31

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**
OS: MacOS Catalina
Browser: FF

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
@vraravam thanks for your contributions 😃 . You are very welcome and sorry for the lack of documentation I have to take care of it. For your question i think a test folder is better

**Comment by vraravam** [comment]
@nicolas63 - I would suggest that the folders and relative positions of the `sln` file, etc follow the convention [here](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-with-cli#testing-the-sample). I have added the `sln` file into the text below:
```
/NewTypes
|__/src
   |__/NewTypes
      |__/Pets
         |__Dog.cs
         |__Cat.cs
         |__IPet.cs
      |__Program.cs
      |__NewTypes.csproj
|__/test
   |__NewTypesTests
      |__PetTests.cs
      |__NewTypesTests.csproj)
|__NewTypes.sln
```

If this is acceptable to you, I will raise a PR with the general structure (and an `assertTrue(true)` dummy test) - and after this is approved, I can start adding unit tests. Would you prefer `xunit` or `nunit`?

**Comment by nicolas63** [comment]
For the structure i'm ok it's like generated app. For test framework Xunit because we have use this on the generated app.

**Comment by vraravam** [comment]
Closing since the PR #5  was merged.
